### ISSUE TITLE
is 100 possible for SSIMULACRA2 with identical files?

### ISSUE THREAD

**Issue by VD-NVencC** [cloudinary/ssimulacra2#10]
there's a port for avisynthplus but I wanted to confirm if it was possible to score 100 with identical files? I've attached some results, and samples I used.

https://github.com/cloudinary/ssimulacra2/assets/71042674/3ffc8e0d-3b3a-4377-8e88-cf036694ec50

![00001](https://github.com/cloudinary/ssimulacra2/assets/71042674/1e1e600b-c154-40ca-8f07-acb1b628af9d)
![00003](https://github.com/cloudinary/ssimulacra2/assets/71042674/b464d209-8359-41da-9da5-b3679d2b1b9d)
![00005](https://github.com/cloudinary/ssimulacra2/assets/71042674/441e867b-3a3c-4ff0-9cb0-7ca757a6b30c)

**Comment by tamaracloudinary** [comment]
Hi there, yes, we return a score in the range -inf..100.

**Comment by jonsneyers** [comment]
Could you clarify how to reproduce the problem you're getting?
I cannot reproduce it:

```
$ ssimulacra2 284050535-1e1e600b-c154-40ca-8f07-acb1b628af9d.png 284050535-1e1e600b-c154-40ca-8f07-acb1b628af9d.png
100.00000000

$ ssimulacra2 284050536-b464d209-8359-41da-9da5-b3679d2b1b9d.png 284050536-b464d209-8359-41da-9da5-b3679d2b1b9d.png
100.00000000

$ ssimulacra2 284050537-441e867b-3a3c-4ff0-9cb0-7ca757a6b30c.png 284050537-441e867b-3a3c-4ff0-9cb0-7ca757a6b30c.png
100.00000000
```

**Comment by VD-NVencC** [comment]
Thank you for sharing your results, I wanted to verify if another project (AviSynthPlus-ssimulacra) was not reaching an expected outcome before going forward. Linux, Rust, and Vapoursynth are out of my wheelhouse (various implementations here on github) and I thought it would be easier to ask.
