### ISSUE TITLE
Add ssimulacra2 results to the MSU benchmark.

### ISSUE THREAD

**Issue by ioctl-user** [cloudinary/ssimulacra2#11]
Please consider adding ssimulacra2 metric results to the [MSU benchark collection](https://videoprocessing.ai/benchmarks/full-reference-video-quality-metrics.html) .

MSU video processing, compression and quality research group conducts comprehensive and in-depth research and has several lines of research: video compression algorithm comparison, video quality measurement an so on.

Among other things, they investigate the correlation of video quality metrics with subjectively perceived quality.

**Comment by jonsneyers** [comment]
Interesting, I sent them an email with some information on ssimulacra2.

Obviously it is only an image metric, not a video metric, but still it could be interesting to investigate correlations when doing a simple frame-by-frame comparison.

**Comment by jonsneyers** [comment]
It looks like ssimulacra2 has been added, at least I see it is now in the list at https://videoprocessing.ai/benchmarks/video-quality-metrics_participants.html
