### ISSUE TITLE
[REQ] Consider adding heatmap function

### ISSUE THREAD

**Issue by derbart84** [cloudinary/ssimulacra2#12]
Please consider adding a function to export a heatmap with the differences between original and distorted. I think it would be very interesting to quickly see the regions with the most distortion.

**Comment by jonsneyers** [comment]
Makes sense, but it's a little tricky to produce a single heatmap, since the final score is based on 108 subscores that are derived from 54 heatmaps. So there are some choices to make in how to visualize that information...

**Comment by derbart84** [comment]
Realizing the complexity, maybe it is better for now to use Kornelski's DSSIM heatmaps
