### ISSUE TITLE
Q: lcms2 version requirement

### ISSUE THREAD

**Issue by m6w6** [cloudinary/ssimulacra2#13]
Current Ubuntu LTS (jammy) ships lcms version 2.12; is there a specific requirement fort v2.13?

Thanks

**Comment by jonsneyers** [comment]
I _think_ version 2.12 should also work — in any case, it should also be possible to build without lcms2 and use skcms instead. Regarding color conversions, ssimulacra2 simply uses internal code from libjxl, so if there are build/platform issues related to this, it may be best to open an issue at the libjxl repo (https://github.com/libjxl/libjxl).

**Comment by m6w6** [comment]
Thanks!
