### ISSUE TITLE
Do we plan to add support for AVIF inputs?

### ISSUE THREAD

**Issue by AmeyMore98** [cloudinary/ssimulacra2#14]
Are we planning on adding support for comparing JPEG/PNG images and their AVIF conversions?

Something like this:
```
ssimulacra2 original.jpeg distorted.avif
```

I understand we can convert the AVIF to PNG for comparison, but will it be as accurate as comparing directly to the AVIF version?

**Comment by jonsneyers** [comment]
AVIF precision is limited to 12-bit, so converting it to PNG (which allows up to 16-bit precision) is fine.

There are no plans to add support for AVIF inputs directly.

**Comment by AmeyMore98** [comment]
Got it, thanks!
