### ISSUE TITLE
Readme and cli help inconsistency

### ISSUE THREAD

**Issue by greentore** [cloudinary/ssimulacra2#15]
The readme gives score descriptions that are inconsistent with help printed by ssimulacra2 when you run it without parameters. For example the readme says that score of 90 `corresponds to the average output of mozjpeg -quality 95 or the p10 output of cjxl -q 95` but according to cli help it's `average output of cjxl -q 90 or mozjpeg -quality 90`. Which one is correct?

**Comment by jonsneyers** [comment]
The readme is more correct. I'll update the descriptions to be consistent.

**Comment by jonsneyers** [comment]
Updated. Thanks for reporting the discrepancy. The descriptions should now be consistent and more accurate.
