### ISSUE TITLE
Building was tricky; README is scant

### ISSUE THREAD

**Issue by eeeps** [cloudinary/ssimulacra2#3]
Using Docker Desktop on an Apple Silicon Mac, this finally worked for me:

```
$ docker run -i -t ubuntu:kinetic /bin/bash
# apt install build-essential git libhwy-dev liblcms2-dev libjpeg-turbo8-dev libpng-dev cmake ninja-build
# git clone https://github.com/cloudinary/ssimulacra2.git
# cd ssimulacra2
# mkdir build
# cd build
# cmake ../src -G Ninja
# ninja ssimulacra2
```

Tricky bits:

1. `ubuntu:latest` pulled jammy; apt on jammy will only install lcms2 version 2.12, but ssimulacra2 requires 2.13.
2. On Ubuntu, the libjpeg-turbo-dev library is called `libjpeg-turbo8-dev`, not libjpeg62-turbo-dev as the instructions state.
3. I needed build-essential to build CXX things.

Dunno if any of this is worth calling out in the install instructions, or if they need to be elaborated/clarified.

Also what I wouldn't do to get this as a homebrew package and/or wasm build! But I digress...

**Comment by jonsneyers** [comment]
Thanks! Added most of this info to the README.
