### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by cdgriffith** [cloudinary/ssimulacra2#5]
After building with `build_ssimulacra_from_libjxl_repo` on WSL Ubuntu 20.04

```
./ssimulacra2 og100.jpg og90.jpg
../tools/ssimulacra2_main.cc:46: JXL_CHECK: SetFromFile(argv[1], jxl::extras::ColorHints(), &io1)
Illegal instruction
```

**Comment by jonsneyers** [comment]
That looks like it couldn't find or load those files for some reason. What does `identify og100.jpg og90.jpg` say?

**Comment by cdgriffith** [comment]
```
identify og.png og100.jpg og90.jpg
og.png PNG 4672x2628 4672x2628+0+0 8-bit sRGB 11.198MiB 0.000u 0:00.000
og100.jpg JPEG 4672x2628 4672x2628+0+0 8-bit sRGB 4.76304MiB 0.000u 0:00.000
og90.jpg JPEG 4672x2628 4672x2628+0+0 8-bit sRGB 2.38245MiB 0.000u 0:00.000
```

These are all exports from lightroom. I changed them to be smaller resolution for sharing and still had the same issue. 

```
identify og_full_small.jpg og_90_small.jpg
og_full_small.jpg JPEG 1920x1920 1920x1920+0+0 8-bit sRGB 2.13527MiB 0.000u 0:00.000
og_90_small.jpg JPEG 1920x1920 1920x1920+0+0 8-bit sRGB 1.29942MiB 0.000u 0:00.000
```

[test_images.zip](https://github.com/cloudinary/ssimulacra2/files/10458157/test_images.zip)

**Comment by jonsneyers** [comment]
I cannot reproduce :(

```
ssimulacra2 og_full_small.jpg og_90_small.jpg 
85.56618206
```

Perhaps you don't have a libjpeg-dev installed and ended up compiling ssimulacra2 without support for jpeg input?

**Comment by cdgriffith** [comment]
I checked and made sure that was installed. I ran the build script again, and for some reason now it works! 

🤷  I wish I knew what was the cause so I could help contribute to that weird edge case. For now though, just happy it's working, thanks for checking on your end or I wouldn't have bothered trying again!
