### ISSUE TITLE
How to build on OSX?

### ISSUE THREAD

**Issue by Zelex** [cloudinary/ssimulacra2#6]
brew installing the various deps doesn't appear to work.

**Comment by momoip** [comment]
Hi @Zelex,
Thanks for reaching out.
Would you please share which steps you have taken and what error did you get?  
Thanks,
Mo

**Comment by Zelex** [comment]
Mostly its complaining about incompatible libpng and libjpeg versions I think. However, since OSX doesn't have apt-get, there are no instructions for OSX at all on how to make it build.

**Comment by momoip** [comment]
Hi @Zelex,
Yes, you're right.  The setup is for a linux environment, e.g. Debian.

**Comment by jonsneyers** [comment]
`brew install jpeg-xl` will include ssimulacra2, if you are just looking for an easy way to run this on macOS.
